export default {
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "25e6d8fd": [() => import(/* webpackChunkName: "25e6d8fd" */ "@site/docs/quizzes/chapter1-section2.md"), "@site/docs/quizzes/chapter1-section2.md", require.resolveWeak("@site/docs/quizzes/chapter1-section2.md")],
  "32d04ea7": [() => import(/* webpackChunkName: "32d04ea7" */ "@site/docs/quizzes/chapter1-section5.md"), "@site/docs/quizzes/chapter1-section5.md", require.resolveWeak("@site/docs/quizzes/chapter1-section5.md")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "6cfccef5": [() => import(/* webpackChunkName: "6cfccef5" */ "/home/ecomw/ai-native-book-phase1/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json"), "/home/ecomw/ai-native-book-phase1/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json", require.resolveWeak("/home/ecomw/ai-native-book-phase1/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json")],
  "729f6499": [() => import(/* webpackChunkName: "729f6499" */ "@site/docs/quizzes/chapter1-section1.md"), "@site/docs/quizzes/chapter1-section1.md", require.resolveWeak("@site/docs/quizzes/chapter1-section1.md")],
  "935f2afb": [() => import(/* webpackChunkName: "935f2afb" */ "~docs/default/version-current-metadata-prop-751.json"), "~docs/default/version-current-metadata-prop-751.json", require.resolveWeak("~docs/default/version-current-metadata-prop-751.json")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "c2089f2c": [() => import(/* webpackChunkName: "c2089f2c" */ "@site/docs/quizzes/chapter1-section3.md"), "@site/docs/quizzes/chapter1-section3.md", require.resolveWeak("@site/docs/quizzes/chapter1-section3.md")],
  "cc0c3b80": [() => import(/* webpackChunkName: "cc0c3b80" */ "@site/docs/chapters/chapter1.md"), "@site/docs/chapters/chapter1.md", require.resolveWeak("@site/docs/chapters/chapter1.md")],
  "d88ba316": [() => import(/* webpackChunkName: "d88ba316" */ "@site/docs/quizzes/chapter1-section4.md"), "@site/docs/quizzes/chapter1-section4.md", require.resolveWeak("@site/docs/quizzes/chapter1-section4.md")],
  "eec94de5": [() => import(/* webpackChunkName: "eec94de5" */ "@site/docs/chapters/template.md"), "@site/docs/chapters/template.md", require.resolveWeak("@site/docs/chapters/template.md")],
  "fd4ca57e": [() => import(/* webpackChunkName: "fd4ca57e" */ "@site/docs/quizzes/chapter1-sections.md"), "@site/docs/quizzes/chapter1-sections.md", require.resolveWeak("@site/docs/quizzes/chapter1-sections.md")],};
